<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEVb45sX\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEVb45sX/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerEVb45sX.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerEVb45sX\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerEVb45sX\appAppKernelProdContainer([
    'container.build_hash' => 'EVb45sX',
    'container.build_id' => '0be23b59',
    'container.build_time' => 1680780488,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEVb45sX');
